[package]
name = "graphics_learn"
version = "0.1.0"
edition = "2021"
authors = ["Blin4ik"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
glam = "0.22.0"